name: Python Tests
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  python-tests:
    name: Python Tests
    runs-on: ubuntu-22.04
    timeout-minutes: 15
    steps:
    - uses: actions/checkout@v3
      with:
        lfs: false
        submodules: 'recursive'
    - uses: actions/setup-python@v4
      with:
        python-version: '3.8'
    - name: Build and install packages
      run: |
        python -m venv .venv
        source .venv/bin/activate
        pip install -e ".[dev,pydantic,dataclasses]"
    - name: Check if generated modules are up-to-date
      run: |
        source .venv/bin/activate
        ./scripts/generate_models.py
        git diff --exit-code HEAD --
    - name: Lint
      run: |
        source .venv/bin/activate
        pysen run format lint
    - name: Run unit test
      run: |
        source .venv/bin/activate
        pytest .
